In [1]:
%load_ext autoreload
%autoreload 2
%load_ext jupyter_black

In [2]:
from pathlib import Path
import polars as pl
from IPython.display import display

# SRC Data

Source data is stored in(dev bucket) /home/jovyan/data/dev/fpipes-f/integration_test/MBD-mini
Loaded from https://huggingface.co/datasets/ai-lab/MBD-mini/tree/main

In [25]:
data_dir = "/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank"
tx_path_str = f"{data_dir}/detail/trx/**/*.parquet"

In [26]:
! ls {data_dir}/detail/trx/**/*.parquet

'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00001-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00085-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00086-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00087-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00088-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00089-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00090-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00091-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00092-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00093-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00094-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00095-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00096-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00097-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00098-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00099-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00100-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00101-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00102-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00103-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00104-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00105-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00106-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00107-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00108-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00109-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00110-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00111-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00112-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00113-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00114-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00115-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00116-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00117-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00118-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00119-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00120-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00121-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00122-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00123-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00124-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00125-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00126-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00127-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00128-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00129-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00130-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00131-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00132-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00133-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00134-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00135-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00136-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00137-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00138-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00139-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00140-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00141-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00142-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00143-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00144-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00145-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00146-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00147-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00148-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00149-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00150-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00151-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00152-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00153-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00154-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00155-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00156-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00157-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00158-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00159-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00160-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00161-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00162-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00163-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00001-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00085-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00086-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00087-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00088-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00089-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00090-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00091-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00092-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00093-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00094-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00095-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00096-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00097-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00098-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00099-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00100-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00101-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00102-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00103-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00104-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00105-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00106-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00107-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00108-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00109-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00110-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00111-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00112-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00113-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00114-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00115-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00116-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00117-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00118-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00119-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00120-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00121-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00122-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00123-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00124-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00125-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00126-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00127-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00128-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00129-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00130-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00131-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00132-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00133-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00134-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00135-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00136-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00137-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00138-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'
'/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=1/part-00139-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet'

In [27]:
dates = [
    "2020-01-01 13:45:48",
    "2020-01-01 16:42:13",
    "2020-01-01 16:45:09",
    "2020-01-02 18:12:48",
    "2020-01-03 19:45:32",
    "2020-01-08 23:16:43",
]
df = pl.DataFrame({"dt": dates, "a": [3, 7, 5, 9, 2, 1]}).with_columns(
    pl.col("dt").str.strptime(pl.Datetime).set_sorted()
)
df.sort("dt")
lf = df.lazy().sort("dt")
out = lf.rolling(index_column="dt", period="2d").agg(
    [
        pl.sum("a").alias("sum_a"),
        pl.min("a").alias("min_a"),
        pl.max("a").alias("max_a"),
    ]
)

In [28]:
lf_tx = pl.scan_parquet(tx_path_str)

# trx profiling

In [29]:
lf_tx.head(n=5).collect()

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ client_id ┆ event_tim ┆ amount    ┆ event_typ ┆ … ┆ src_type2 ┆ src_type2 ┆ src_type3 ┆ src_type │
│ ---       ┆ e         ┆ ---       ┆ e         ┆   ┆ 1         ┆ 2         ┆ 1         ┆ 32       │
│ str       ┆ ---       ┆ f32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ datetime[ ┆           ┆ i32       ┆   ┆ i32       ┆ i32       ┆ i32       ┆ i32      │
│           ┆ ns]       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 01a1aca15 ┆ 2022-10-2 ┆ 1.0215e6  ┆ 16        ┆ … ┆ 21490     ┆ 83        ┆ 364       ┆ 58       │
│ 31e0d86b6 ┆ 6 13:58:5 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 05759fedd ┆ 9.938408  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 36e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 01a1aca15 ┆ 2021-02-0 ┆ 300765.56 ┆ 1         ┆ … ┆ 21490     ┆ 83        ┆ 364       ┆ 58       │
│ 31e0d86b6 ┆ 9 07:43:2 ┆ 25        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 05759fedd ┆ 0.639579  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 36e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 01a1aca15 ┆ 2022-10-2 ┆ 606154.93 ┆ 16        ┆ … ┆ 21490     ┆ 83        ┆ 364       ┆ 58       │
│ 31e0d86b6 ┆ 2 09:12:0 ┆ 75        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 05759fedd ┆ 6.614108  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 36e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 01a1aca15 ┆ 2021-02-1 ┆ 80325.914 ┆ 1         ┆ … ┆ 21490     ┆ 83        ┆ 364       ┆ 58       │
│ 31e0d86b6 ┆ 2 15:12:2 ┆ 062       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 05759fedd ┆ 0.660481  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 36e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 01a1aca15 ┆ 2022-10-0 ┆ 122286.59 ┆ 16        ┆ … ┆ 21490     ┆ 83        ┆ 364       ┆ 58       │
│ 31e0d86b6 ┆ 8 06:52:2 ┆ 375       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 05759fedd ┆ 8.877461  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 36e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
max_min_date = lf_tx.select(
    pl.col("event_time").dt.date().max().alias("max_date"),
    pl.col("event_time").dt.date().min().alias("min_date"),
).collect()
date_range = max_min_date["max_date"].item() - max_min_date["min_date"].item()

In [31]:
n_clients = lf_tx.select(pl.col("client_id").n_unique()).collect()
display(n_clients)

shape: (1, 1)
┌───────────┐
│ client_id │
│ ---       │
│ u32       │
╞═══════════╡
│ 98721     │
└───────────┘

In [ ]:
q = lf_tx.select(pl.col("client_id").value_counts())
q = (
    q.collect()
    .select(pl.col("client_id").struct.field("count"))
    .filter(pl.col("count") < 10000)
)
display(q.select(pl.len()))
q["count"].hist(bin_count=10).sort("breakpoint")

shape: (1, 1)
┌───────┐
│ len   │
│ ---   │
│ u32   │
╞═══════╡
│ 98708 │
└───────┘

shape: (10, 3)
┌────────────┬──────────────────┬───────┐
│ breakpoint ┆ category         ┆ count │
│ ---        ┆ ---              ┆ ---   │
│ f64        ┆ cat              ┆ u32   │
╞════════════╪══════════════════╪═══════╡
│ 998.3      ┆ [1.0, 998.3]     ┆ 88697 │
│ 1995.6     ┆ (998.3, 1995.6]  ┆ 8508  │
│ 2992.9     ┆ (1995.6, 2992.9] ┆ 1201  │
│ 3990.2     ┆ (2992.9, 3990.2] ┆ 191   │
│ 4987.5     ┆ (3990.2, 4987.5] ┆ 70    │
│ 5984.8     ┆ (4987.5, 5984.8] ┆ 23    │
│ 6982.1     ┆ (5984.8, 6982.1] ┆ 4     │
│ 7979.4     ┆ (6982.1, 7979.4] ┆ 4     │
│ 8976.7     ┆ (7979.4, 8976.7] ┆ 6     │
│ 9974.0     ┆ (8976.7, 9974.0] ┆ 4     │
└────────────┴──────────────────┴───────┘

# Proto asset ops

In [33]:
lf_tx_part = lf_tx.filter(pl.col("client_id").cast(pl.String).hash() % 100 == 0)
n_client_in_part = lf_tx_part.select(pl.col("client_id").n_unique()).collect()
n_date_part = lf_tx_part.select(pl.col("event_time").dt.date().n_unique()).collect()
print(n_client_in_part)
print(n_date_part)

shape: (1, 1)
┌───────────┐
│ client_id │
│ ---       │
│ u32       │
╞═══════════╡
│ 986       │
└───────────┘
shape: (1, 1)
┌────────────┐
│ event_time │
│ ---        │
│ u32        │
╞════════════╡
│ 731        │
└────────────┘

In [34]:
lf_tx_part = lf_tx.filter(pl.col("client_id").cast(pl.String).hash() % 100 == 0)
n_client_in_part = lf_tx_part.select(pl.col("client_id").n_unique())
print(n_client_in_part)
out = (
    lf_tx_part.sort("event_time")
    .select(pl.col("event_time").dt.date(), pl.col("client_id"), pl.col("amount"))
    .rolling(index_column="event_time", period="1w", group_by="client_id")
    .agg(
        [
            pl.sum("amount").alias("sum_a"),
        ]
    )
    .collect()
)

naive plan: (run LazyFrame.explain(optimized=True) to see the optimized plan)

SELECT [col("client_id").n_unique()]
  FILTER [([(col("client_id").hash()) % (100)]) == (0)]
  FROM
    Parquet SCAN [/home/chemi_t/Documents/sci_fi/Programming/Job/Ameriabank/detail/trx/fold=0/part-00001-f1f2463d-80e2-4335-8981-4fc9e73f56f4.c000.snappy.parquet, ... 399 other sources]
    PROJECT */14 COLUMNS
    ESTIMATED ROWS: 3154000

In [35]:
out.select(pl.col("client_id"), pl.col("event_time").dt.date().alias("date")).group_by(
    "client_id"
).agg(pl.col("date").len())

shape: (986, 2)
┌─────────────────────────────────┬──────┐
│ client_id                       ┆ date │
│ ---                             ┆ ---  │
│ str                             ┆ u32  │
╞═════════════════════════════════╪══════╡
│ e436b34256bd73d6c2c70999804c28… ┆ 662  │
│ c1ec61ceab7d7d055559fde884fcad… ┆ 16   │
│ aa3e88d254520d4532b6ef1c1c35fb… ┆ 2    │
│ 3c6f299fbfd77ce5258b746b7c02e9… ┆ 3    │
│ a96537c14bb64087b3c0519c0cf9d2… ┆ 242  │
│ …                               ┆ …    │
│ 3a698d88313a1cd29741d1607f3189… ┆ 447  │
│ 0f2601af00b819159b2e61b1c4cb66… ┆ 707  │
│ e6b028357bae5c165a910a78131cdf… ┆ 1202 │
│ d32500c239f18ff9ab2ed097246e5c… ┆ 251  │
│ 6c7d45fccfa86e7cc733b1053adb69… ┆ 105  │
└─────────────────────────────────┴──────┘

In [ ]:
date_range.days

AttributeError: 'datetime.timedelta' object has no attribute 'dt'

In [38]:
out.select(pl.len())

shape: (1, 1)
┌────────┐
│ len    │
│ ---    │
│ u32    │
╞════════╡
│ 367964 │
└────────┘